### ISSUE TITLE
30. Jan. 2020: Laravel Usergroup v3.0

### ISSUE THREAD

**Issue by zappzerapp** [real-media-technic-staudacher/laravel-usergroup-nuernberg#5]
### Themen zur Abstimmung:
https://github.com/real-media-technic-staudacher/laravel-usergroup-nuernberg/issues

### Bestätigte Themen:
https://github.com/real-media-technic-staudacher/laravel-usergroup-nuernberg/labels/approved

### Teilnehmer:
Bitte sich irgendwie in den Kommentaren bemerkbar machen 👍

**Comment by zappzerapp** [comment]
✌️

**Comment by zappzerapp** [comment]
## News

### Laravel 6.11.0

***firstWhere***

```
// Before
User::where('emaill', 'foo@bar.com')->first();

// After
User::firstWhere('email', 'foo@bar.com');
```

### Laravel 6.12.0

***Load Factories from a Package***

```
// from a service provider...
$this->loadFactoriesFrom('source/database/factories');

$this->loadFactoriesFrom([
    'source_one/database/factories', 
    'source_two/database/factories',
]);
```

***Factory Builder createMany()***

```
// Before
factory(User::class)->create([
    'name' => 'Taylor',
]);

factory(User::class)->create([
    'name' => 'John',
]);

// After
factory(User::class)->createMany([
    ['name' => 'Taylor'],
    ['name' => 'John'],
]);
```

### Laravel 6.13.0

***Implicit Validation***

```
// Instead of "0.age must be an integer"
// A formatter could do: "age at line 1 must be an integer"
validator(
    ['*.age' => 'integer']
)->setImplicitAttributesFormatter(function ($attribute) {
    [$line, $attribute] = explode('.', $attribute);

    return sprintf('%s at line %d', $attribute, $line + 1);
})->validate();
```

***ensureDirectoryExists***

```
Filesystem::ensureDirectoryExists($path, $mode = 0755, $recursive = true);
```

### Laravel Shared Data

- https://github.com/coderello/laravel-shared-data

### PHP 7.4 Preloading

- https://stitcher.io/blog/php-preload-benchmarks

**Comment by zappzerapp** [comment]
### PHP Benchmarks
* https://kinsta.com/blog/php-benchmarks/

**Comment by zappzerapp** [comment]
### Laravel Valet (@patriziotomato) 
* https://laravel.com/docs/6.x/valet

**Comment by zappzerapp** [comment]
### Laravel Totem (@adrian-schnell)
* https://github.com/codestudiohq/laravel-totem

**Comment by quaddy** [comment]
🥇
